AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Bio Encyclopedia Serverless Pipeline

Parameters:
  DBHost:
    Type: String
    Description: RDS Endpoint URL
  DBSecretArn:
    Type: String
    Description: Secret ARN for RDS Credentials
  VpcSubnetId:
    Type: String
    Description: VPC Subnet ID for Load Lambda
  VpcSecurityGroupId:
    Type: String
    Description: Security Group ID for Load Lambda

Globals:
  Function:
    Timeout: 60
    Runtime: python3.11
    Environment:
      Variables:
        DATA_BUCKET_NAME: !Ref EcoDataBucket

Resources:
  EcoDataBucket:
    Type: AWS::S3::Bucket

  CrawlingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handlers.crawling_handler.lambda_handler
      Policies:
        - S3WritePolicy:
            BucketName: !Ref EcoDataBucket

  ExtractFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handlers.extract_handler.lambda_handler
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref EcoDataBucket
        - S3WritePolicy:
            BucketName: !Ref EcoDataBucket

  PreprocessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handlers.preprocess_handler.lambda_handler
      Timeout: 120 # Image processing takes longer
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref EcoDataBucket
        - S3WritePolicy:
            BucketName: !Ref EcoDataBucket

  LoadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handlers.load_handler.lambda_handler
      VpcConfig:
        SecurityGroupIds:
          - !Ref VpcSecurityGroupId
        SubnetIds:
          - !Ref VpcSubnetId
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_SECRET_ARN: !Ref DBSecretArn
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref EcoDataBucket
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DBSecretArn

  DispatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: handlers.dispatcher_handler.lambda_handler
      VpcConfig:
        SecurityGroupIds:
          - !Ref VpcSecurityGroupId
        SubnetIds:
          - !Ref VpcSubnetId
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_SECRET_ARN: !Ref DBSecretArn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DBSecretArn

  DataPipelineStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: Dispatcher
        States:
          Dispatcher:
            Type: Task
            Resource: !GetAtt DispatcherFunction.Arn
            Next: MapSpecies
          MapSpecies:
            Type: Map
            ItemsPath: "$.target_species"
            MaxConcurrency: 3
            Iterator:
              StartAt: Crawl
              States:
                Crawl:
                  Type: Task
                  Resource: !GetAtt CrawlingFunction.Arn
                  Next: Extract
                Extract:
                  Type: Task
                  Resource: !GetAtt ExtractFunction.Arn
                  Next: Preprocess
                Preprocess:
                  Type: Task
                  Resource: !GetAtt PreprocessFunction.Arn
                  Next: Load
                Load:
                  Type: Task
                  Resource: !GetAtt LoadFunction.Arn
                  End: true
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref DispatcherFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CrawlingFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ExtractFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref PreprocessFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadFunction
      Events:
        DailyRun:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "cron(0 15 * * ? *)"
            Name: "EcoDataDailySchedule"
